services:
  backend:
    container_name: backend
    build: backend
    env_file: backend/.env
    volumes: 
      - database:/app/db
    secrets:
      - vault_token
    networks: 
      - transcendance
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN_FILE=/run/secrets/vault_token
      - DATABASE_URL=db/database.sqlite
    ports: 
      - "8080:8080"
    depends_on:
      - vault
    restart: always

  vault:
    container_name: vault
    build: vault
    # TODO: change ports to expose: "8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - transcendance
    volumes: 
      - vault:/vault/data
    restart: always

volumes:
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../.volumes/db'
  vault:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../.volumes/vault'
        
networks:
  transcendance:
    name: transcendance
    driver: bridge

secrets:
  vault_token:
    file: ../.secrets/vault-token.txt
  