services:
  backend:
    container_name: backend
    build: backend
    env_file: backend/.env
    volumes: 
      - database:/app/db
    networks: 
      - transcendance
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - DATABASE_URL=db/database.sqlite
    ports: 
      - "8080:8080"
    depends_on:
      vault:
        condition: service_healthy
    restart: always

  vault:
    container_name: vault
    build: vault
    # TODO: change ports to expose: "8200"
    ports:
      - "8200:8200"
    # TODO: env var for the "dev-mode", suppress and add config file for vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - transcendance
    restart: always
    healthcheck:
      test: ["CMD", "sh", "-c", "VAULT_ADDR='http://127.0.0.1:8200' VAULT_TOKEN='root' vault status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

    
volumes:
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../.volumes/db'
        
networks:
  transcendance:
    name: transcendance
    driver: bridge

  # secrets:
  